import new.error.errors as sett_err


def test_dictionary_with_errors():
    sett_err.dictionary_with_errors()
    pass
